# Generated by Django 5.2.3 on 2026-09-27 11:09

import datetime

from django.db import migrations, models

OLD_DEFAULT_DAYS = 3
NEW_DEFAULT_DAYS = 180


def extend_expiry(apps, schema_editor):
    """Move the live settings row off the old 3-day default and give every unused code the
    new lifetime (counted from when it was created), including ones that lapsed under the
    short window — agents may still be holding screenshots of them."""
    ReferralSettings = apps.get_model("referrals", "ReferralSettings")
    ReferralCode = apps.get_model("referrals", "ReferralCode")

    ReferralSettings.objects.filter(code_expiry_days=OLD_DEFAULT_DAYS).update(code_expiry_days=NEW_DEFAULT_DAYS)

    lifetime = datetime.timedelta(days=NEW_DEFAULT_DAYS)
    for code in ReferralCode.objects.filter(is_used=False):
        new_expiry = code.created_at + lifetime
        if new_expiry > code.expires_at:
            code.expires_at = new_expiry
            code.save(update_fields=["expires_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralsettings',
            name='code_expiry_days',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.RunPython(extend_expiry, migrations.RunPython.noop),
    ]
